### ISSUE TITLE
Setting Permissions for "Default" and "Anonymous" Accounts

### ISSUE THREAD

**Issue by sascha224** [Tristanic1/Set-MailboxFolderPermissionsGUI#2]
Is there a way to set permissions for "Default" ("Standard" in german language) and "Anonymous" ("Anonym")? If I try it, I get an message that this is not a valid username. It would be nice if that would work, because many of our mailboxes have odd "Default" permissions.

**Comment by Tristanic1** [comment]
Hi @sascha224 , I think so - those accounts have well-known SIDS, so shouldn't be an issue. 
I'll check in next few days.

**Comment by Tristanic1** [comment]
@sascha224 this functionality has been added in the latest release, please test and let me know if it works as expected.

**Comment by sascha224** [comment]
With this release, I have a new problem: I can set Access rights for the Default and Anonymous user, but adding rights for any other user doesn't work anymore. With the old version 0.2, it works again.
The second problem: The "Check" button shows rights for our "Anonym" and "Standard" (the german translation) users, even if the checkbox is disabled.

**Comment by Tristanic1** [comment]
@sascha224 thanks for the feedback.
I think I've fixed the issues, let me know if it works now.

**Comment by sascha224** [comment]
Now it works like expected! Thanks a lot, your script is very helpful for me!
